# Generated by Django 3.0.6 on 2020-09-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='designation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
