# Generated by Django 3.0.6 on 2020-05-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0003_managerdetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddocumentmodel',
            name='csv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saveddocumentmodel',
            name='doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saveddocumentmodel',
            name='docx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saveddocumentmodel',
            name='jpeg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saveddocumentmodel',
            name='pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saveddocumentmodel',
            name='ppt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saveddocumentmodel',
            name='xls',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='manager',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='normal_user',
            field=models.BooleanField(default=0),
        ),
    ]
