# Generated by Django 3.0.6 on 2020-09-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0004_managerdetails_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletiming',
            name='break_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduletiming',
            name='offline_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduletiming',
            name='online_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
