# Generated by Django 3.0.6 on 2020-06-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0006_taskmodel_acknowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
