# Generated by Django 3.0.6 on 2020-09-24 06:14

from django.db import migrations, models
import normal_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0006_auto_20200924_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletiming',
            name='break_time',
            field=models.TimeField(blank=True, default=normal_user.models.default_start_time, null=True),
        ),
        migrations.AlterField(
            model_name='scheduletiming',
            name='offline_time',
            field=models.TimeField(blank=True, default=normal_user.models.default_start_time, null=True),
        ),
        migrations.AlterField(
            model_name='scheduletiming',
            name='online_time',
            field=models.TimeField(blank=True, default=normal_user.models.default_start_time, null=True),
        ),
    ]
