# Generated by Django 3.0.6 on 2020-06-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0007_taskmodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='date_str',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
