# Generated by Django 3.0.6 on 2020-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0008_taskmodel_date_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
