# Generated by Django 3.0.6 on 2020-06-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0009_emailmodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmodel',
            name='alert_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
