# Generated by Django 3.0.6 on 2020-09-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0010_auto_20200924_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletiming',
            name='break_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='scheduletiming',
            name='offline_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='scheduletiming',
            name='online_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
