# Generated by Django 3.0.6 on 2020-06-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0010_alertmodel_alert_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdetails',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
