# Generated by Django 3.0.6 on 2020-06-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0013_onlinestatusmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinestatusmodel',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
