# Generated by Django 3.0.6 on 2020-06-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0014_auto_20200610_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='seen_unseen',
            field=models.BooleanField(default=False),
        ),
    ]
