# Generated by Django 3.0.6 on 2020-06-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0015_taskmodel_seen_unseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertmodel',
            name='seen_unseen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='seen_unseen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='seen_unseen',
            field=models.BooleanField(default=False),
        ),
    ]
