# Generated by Django 3.0.6 on 2020-06-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0016_auto_20200612_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='email_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
