# Generated by Django 3.0.6 on 2020-06-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0018_functions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffstatusmodel',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
