# Generated by Django 3.0.6 on 2020-06-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0021_emailmodel_date_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='it_equipment_specification',
            field=models.TextField(blank=True),
        ),
    ]
