# Generated by Django 3.0.6 on 2020-06-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0022_auto_20200618_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletiming',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduletiming',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
