# Generated by Django 3.0.6 on 2020-06-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0023_auto_20200620_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletiming',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduletiming',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
