# Generated by Django 3.0.6 on 2020-06-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0026_auto_20200625_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatthread',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='chatthread',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatThread',
        ),
    ]
