# Generated by Django 3.0.6 on 2020-06-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0028_chatmessage_chatthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
