# Generated by Django 3.0.6 on 2020-06-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0032_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdetails',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
