# Generated by Django 3.0.6 on 2020-06-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0033_managerdetails_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerdetails',
            old_name='function',
            new_name='designation',
        ),
    ]
