# Generated by Django 3.0.6 on 2020-06-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0034_auto_20200629_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerdetails',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
