# Generated by Django 3.0.6 on 2020-06-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0036_saveddocumentmodel_pptx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
