# Generated by Django 3.0.6 on 2020-06-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0037_auto_20200629_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='descrtiption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailmodel',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
