# Generated by Django 3.0.6 on 2020-07-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0038_auto_20200630_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
