# Generated by Django 3.0.6 on 2020-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0040_emailmodel_created_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='archive_2',
            field=models.BooleanField(default=False),
        ),
    ]
