# Generated by Django 3.0.6 on 2020-07-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0042_saveddocumentmodel_xlsx'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddocumentmodel',
            name='jpg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saveddocumentmodel',
            name='png',
            field=models.BooleanField(default=False),
        ),
    ]
