# Generated by Django 3.0.6 on 2020-07-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0043_auto_20200720_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
