# Generated by Django 3.0.6 on 2020-07-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0044_auto_20200720_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
