# Generated by Django 3.0.6 on 2020-07-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0045_chatmessage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='cities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='departments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='functions',
            name='function',
            field=models.TextField(blank=True, null=True),
        ),
    ]
