# Generated by Django 3.0.6 on 2020-07-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0046_auto_20200724_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='date_str',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
