# Generated by Django 3.0.6 on 2020-07-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0047_auto_20200726_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerdetails',
            name='designation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
