# Generated by Django 3.0.6 on 2020-07-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0048_auto_20200727_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='from_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='to_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
