# Generated by Django 3.0.6 on 2020-07-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0049_auto_20200727_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmodel',
            old_name='created',
            new_name='created_staff',
        ),
    ]
