# Generated by Django 3.0.6 on 2020-07-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0050_auto_20200727_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='created',
            new_name='created_manager',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='created_staff',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
