# Generated by Django 3.0.6 on 2020-07-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0051_auto_20200727_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffstatusmodel',
            old_name='created',
            new_name='created_manager',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='created_staff',
            new_name='created',
        ),
        migrations.AddField(
            model_name='staffstatusmodel',
            name='created_staff',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
