# Generated by Django 3.0.6 on 2020-07-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0052_auto_20200727_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddocumentmodel',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
