# Generated by Django 3.0.6 on 2020-07-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0053_auto_20200727_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='last_countdown_timer_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
