# Generated by Django 3.0.6 on 2020-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0056_chatthread_date_updated_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinestatusmodel',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
