# Generated by Django 3.0.6 on 2020-08-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normal_user', '0058_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='seen_unseen',
            field=models.BooleanField(default=False),
        ),
    ]
